// Lago Quieto — modo Idle: dados de economia v3 (prop "v3-final", scripts/econ-props/prop-v3-final.json).
// clickPower = (clickBase·clickMult + clickPct·rate) · prestígio · combo; clickPct = clickPctBase + Σ pct das Pedras pesadas (máx 0.48).
// Marcos ×1.5 em 10/25/50/100 e ×2 em 250 (grátis). Geradores só entram na loja quando gen.era ≤ era atual (eras por life acumulado).
// Sim (perfil ativo, combo 1.3): 1ª compra 4 s; 5 distintas 2m47; gap máx 11 s; aurora 43m59; taxa 30 min 60.6K/s;
// clique 27% aos 30 min / 16% aos 60; eras 2m47 / 9m44 / 19m50 / 33m11 / 45m22; 1º prestígio 55 min (taxa 1.08M/s).
window.LQ = window.LQ || {};
LQ.IdleData = {
  clickBase: 1,
  clickPctBase: 0.12,
  gens: [
    {"id":"vagalume","icon":"ic-firefly","unlock":"fireflies","era":0,"base":8,"growth":1.13,"rate":0.25,"name":"Vagalumes","desc":"mais vagalumes no lago","milestones":[{"at":1,"text":"3 vagalumes acendem"},{"at":5,"text":"9 · pousam nos juncos (se houver)"},{"at":10,"text":"12 · formam constelações"},{"at":25,"text":"enxame de 15"}]},
    {"id":"juncos","icon":"ic-reed","unlock":"wind","era":0,"base":40,"growth":1.13,"rate":1.2,"name":"Juncos","desc":"mais juncos na margem","milestones":[{"at":1,"text":"3 brotam à esquerda"},{"at":5,"text":"chegam à direita (9)"},{"at":10,"text":"12 juncos"},{"at":25,"text":"margem cheia (15)"}]},
    {"id":"peixe","icon":"ic-fish","unlock":"fish","era":1,"base":180,"growth":1.13,"rate":5,"name":"Peixes","desc":"+1 peixe · come pedras","milestones":[{"at":1,"text":"come as pedras (×2)"},{"at":5,"text":"3 peixes · saltam sozinhos"},{"at":10,"text":"comem as pedras (×3)"},{"at":25,"text":"cardume de 5"}]},
    {"id":"estrelas","icon":"ic-star","unlock":"stars2","era":1,"base":800,"growth":1.15,"rate":20,"name":"Estrelas","desc":"céu mais estrelado","milestones":[{"at":1,"text":"15 estrelas"},{"at":5,"text":"céu denso (45)"},{"at":10,"text":"cadentes frequentes"},{"at":25,"text":"75 estrelas"}]},
    {"id":"lua","icon":"ic-moon","unlock":"moon","era":2,"base":3000,"growth":1.15,"rate":70,"name":"Lua","desc":"lua e halo maiores","milestones":[{"at":5,"text":"lua cheia maior"},{"at":10,"text":"nuvens"},{"at":25,"text":"halo dourado"},{"at":50,"text":"lua enorme"}]},
    {"id":"dourado","icon":"ic-goldfish","unlock":"fish2","era":2,"base":12000,"growth":1.15,"rate":250,"name":"Peixe dourado","desc":"+1 dourado (até 3)","milestones":[{"at":1,"text":"1º dourado"},{"at":5,"text":"3 dourados"}]},
    {"id":"nevoa","icon":"ic-mountain","unlock":"fog_clear","era":3,"base":55000,"growth":1.16,"rate":600,"name":"Montanhas","desc":"cordilheiras ao fundo","milestones":[{"at":1,"text":"névoa abre"},{"at":2,"text":"3ª cordilheira"},{"at":5,"text":"4ª cordilheira"}]},
    {"id":"lirio","icon":"ic-lily","unlock":"lilies","era":3,"base":250000,"growth":1.16,"rate":2200,"name":"Lírios","desc":"mais lírios na água","milestones":[{"at":1,"text":"3 lírios"},{"at":5,"text":"5 lírios · toque para florir"},{"at":25,"text":"7 lírios"}]},
    {"id":"sapo","icon":"ic-frog","unlock":"frog","era":4,"base":1000000,"growth":1.16,"rate":13000,"name":"Sapos","desc":"+1 sapo coaxando","milestones":[{"at":1,"text":"1º coaxo"},{"at":5,"text":"coro de 3 sapos"},{"at":25,"text":"5 sapos"}]},
    {"id":"aurora","icon":"ic-aurora","unlock":"aurora","era":4,"base":2800000,"growth":1.16,"rate":60000,"name":"Aurora","desc":"aurora no céu","milestones":[{"at":1,"text":"1ª faixa"},{"at":10,"text":"duas faixas"}]},
  ],
  upgrades: [
    {"id":"vagalume_10","gen":"vagalume","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Vagalumes","desc":"produção de vagalumes ×1.5 aos 10"},
    {"id":"vagalume_25","gen":"vagalume","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Vagalumes","desc":"produção de vagalumes ×1.5 aos 25"},
    {"id":"vagalume_50","gen":"vagalume","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Vagalumes","desc":"produção de vagalumes ×1.5 aos 50"},
    {"id":"vagalume_100","gen":"vagalume","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Vagalumes","desc":"produção de vagalumes ×1.5 aos 100"},
    {"id":"vagalume_250","gen":"vagalume","kind":"mult","at":250,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 250"},
    {"id":"juncos_10","gen":"juncos","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Juncos","desc":"produção de juncos ×1.5 aos 10"},
    {"id":"juncos_25","gen":"juncos","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Juncos","desc":"produção de juncos ×1.5 aos 25"},
    {"id":"juncos_50","gen":"juncos","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Juncos","desc":"produção de juncos ×1.5 aos 50"},
    {"id":"juncos_100","gen":"juncos","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Juncos","desc":"produção de juncos ×1.5 aos 100"},
    {"id":"juncos_250","gen":"juncos","kind":"mult","at":250,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 250"},
    {"id":"peixe_10","gen":"peixe","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Peixes","desc":"produção de peixes ×1.5 aos 10"},
    {"id":"peixe_25","gen":"peixe","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Peixes","desc":"produção de peixes ×1.5 aos 25"},
    {"id":"peixe_50","gen":"peixe","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Peixes","desc":"produção de peixes ×1.5 aos 50"},
    {"id":"peixe_100","gen":"peixe","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Peixes","desc":"produção de peixes ×1.5 aos 100"},
    {"id":"peixe_250","gen":"peixe","kind":"mult","at":250,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 250"},
    {"id":"estrelas_10","gen":"estrelas","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Estrelas","desc":"produção de estrelas ×1.5 aos 10"},
    {"id":"estrelas_25","gen":"estrelas","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Estrelas","desc":"produção de estrelas ×1.5 aos 25"},
    {"id":"estrelas_50","gen":"estrelas","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Estrelas","desc":"produção de estrelas ×1.5 aos 50"},
    {"id":"estrelas_100","gen":"estrelas","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Estrelas","desc":"produção de estrelas ×1.5 aos 100"},
    {"id":"estrelas_250","gen":"estrelas","kind":"mult","at":250,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 250"},
    {"id":"lua_10","gen":"lua","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Lua","desc":"produção de lua ×1.5 aos 10"},
    {"id":"lua_25","gen":"lua","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Lua","desc":"produção de lua ×1.5 aos 25"},
    {"id":"lua_50","gen":"lua","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Lua","desc":"produção de lua ×1.5 aos 50"},
    {"id":"lua_100","gen":"lua","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Lua","desc":"produção de lua ×1.5 aos 100"},
    {"id":"lua_250","gen":"lua","kind":"mult","at":250,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 250"},
    {"id":"dourado_10","gen":"dourado","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Peixe dourado","desc":"produção de peixe dourado ×1.5 aos 10"},
    {"id":"dourado_25","gen":"dourado","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Peixe dourado","desc":"produção de peixe dourado ×1.5 aos 25"},
    {"id":"dourado_50","gen":"dourado","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Peixe dourado","desc":"produção de peixe dourado ×1.5 aos 50"},
    {"id":"dourado_100","gen":"dourado","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Peixe dourado","desc":"produção de peixe dourado ×1.5 aos 100"},
    {"id":"dourado_250","gen":"dourado","kind":"mult","at":250,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 250"},
    {"id":"nevoa_10","gen":"nevoa","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Montanhas","desc":"produção de montanhas ×1.5 aos 10"},
    {"id":"nevoa_25","gen":"nevoa","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Montanhas","desc":"produção de montanhas ×1.5 aos 25"},
    {"id":"nevoa_50","gen":"nevoa","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Montanhas","desc":"produção de montanhas ×1.5 aos 50"},
    {"id":"nevoa_100","gen":"nevoa","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Montanhas","desc":"produção de montanhas ×1.5 aos 100"},
    {"id":"nevoa_250","gen":"nevoa","kind":"mult","at":250,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 250"},
    {"id":"lirio_10","gen":"lirio","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Lírios","desc":"produção de lírios ×1.5 aos 10"},
    {"id":"lirio_25","gen":"lirio","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Lírios","desc":"produção de lírios ×1.5 aos 25"},
    {"id":"lirio_50","gen":"lirio","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Lírios","desc":"produção de lírios ×1.5 aos 50"},
    {"id":"lirio_100","gen":"lirio","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Lírios","desc":"produção de lírios ×1.5 aos 100"},
    {"id":"lirio_250","gen":"lirio","kind":"mult","at":250,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 250"},
    {"id":"sapo_10","gen":"sapo","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Sapos","desc":"produção de sapos ×1.5 aos 10"},
    {"id":"sapo_25","gen":"sapo","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Sapos","desc":"produção de sapos ×1.5 aos 25"},
    {"id":"sapo_50","gen":"sapo","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Sapos","desc":"produção de sapos ×1.5 aos 50"},
    {"id":"sapo_100","gen":"sapo","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Sapos","desc":"produção de sapos ×1.5 aos 100"},
    {"id":"sapo_250","gen":"sapo","kind":"mult","at":250,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 250"},
    {"id":"aurora_10","gen":"aurora","kind":"mult","at":10,"cost":null,"value":1.5,"name":"Aurora","desc":"produção de aurora ×1.5 aos 10"},
    {"id":"aurora_25","gen":"aurora","kind":"mult","at":25,"cost":null,"value":1.5,"name":"Aurora","desc":"produção de aurora ×1.5 aos 25"},
    {"id":"aurora_50","gen":"aurora","kind":"mult","at":50,"cost":null,"value":1.5,"name":"Aurora","desc":"produção de aurora ×1.5 aos 50"},
    {"id":"aurora_100","gen":"aurora","kind":"mult","at":100,"cost":null,"value":1.5,"name":"Aurora","desc":"produção de aurora ×1.5 aos 100"},
    {"id":"aurora_250","gen":"aurora","kind":"mult","at":250,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 250"},
    {"id":"click_1","gen":null,"kind":"click","at":null,"cost":15,"value":2,"pct":0.06,"name":"Pedras pesadas I","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"click_2","gen":null,"kind":"click","at":null,"cost":150,"value":2,"pct":0.06,"name":"Pedras pesadas II","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"click_3","gen":null,"kind":"click","at":null,"cost":1500,"value":2,"pct":0.06,"name":"Pedras pesadas III","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"click_4","gen":null,"kind":"click","at":null,"cost":15000,"value":2,"pct":0.06,"name":"Pedras pesadas IV","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"click_5","gen":null,"kind":"click","at":null,"cost":150000,"value":2,"pct":0.06,"name":"Pedras pesadas V","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"click_6","gen":null,"kind":"click","at":null,"cost":1500000,"value":2,"pct":0.06,"name":"Pedras pesadas VI","desc":"cada pedra rende ×2 e +6% do lago"},
    {"id":"auto_1","gen":null,"kind":"auto","at":null,"cost":800,"value":1,"name":"Orvalho +1/s","desc":"anéis automáticos +1/s"},
    {"id":"auto_2","gen":null,"kind":"auto","at":null,"cost":40000,"value":2,"name":"Orvalho +2/s","desc":"anéis automáticos +2/s"},
    {"id":"offline_12h","gen":null,"kind":"offline","at":null,"cost":15000,"value":12,"name":"Sono 12h","desc":"ganho offline até 12h"},
    {"id":"offline_18h","gen":null,"kind":"offline","at":null,"cost":300000,"value":18,"name":"Sono 18h","desc":"ganho offline até 18h"},
    {"id":"offline_24h","gen":null,"kind":"offline","at":null,"cost":4000000,"value":24,"name":"Sono 24h","desc":"ganho offline até 24h"},
    {"id":"racao","gen":null,"kind":"racao","at":null,"cost":20000,"value":4,"name":"Ração","desc":"pedras viram ração; peixes comem ×4"},
  ],
  prestige: {"K":700000000},
  // Eras "A Margem que Acende": limiar em life acumulado (persiste no prestígio); gens liberados na loja; peça permanente na margem.
  eras: [
    {"id":"escuro","name":"Lago Escuro","life":0,"gens":["vagalume","juncos"],"piece":"none","toast":{"title":"Lago Escuro","text":"Só a água e o silêncio. Jogue uma pedra."}},
    {"id":"acordado","name":"Lago Acordado","life":7000,"gens":["peixe","estrelas"],"piece":"lantern","toast":{"title":"Lago Acordado","text":"Alguém acendeu uma lanterna na margem. Vagalumes fogem das ondas… será que cabem nela?"}},
    {"id":"vivo","name":"Lago Vivo","life":400000,"gens":["lua","dourado"],"piece":"pier","toast":{"title":"Lago Vivo","text":"Um píer de madeira cresceu na margem direita. A lua e o peixe dourado se aproximam."}},
    {"id":"profundo","name":"Lago Profundo","life":7500000,"gens":["nevoa","lirio"],"piece":"boat","toast":{"title":"Lago Profundo","text":"Um barco amarrado ao píer e três luzes na outra margem: alguém mora ali."}},
    {"id":"lendario","name":"Lago Lendário","life":55000000,"gens":["sapo","aurora"],"piece":"bridge","toast":{"title":"Lago Lendário","text":"Uma ponte em arco leva às montanhas. No templo, uma janela acesa."}},
    {"id":"amanhecer","name":"Amanhecer","life":200000000,"gens":[],"piece":"dawn","toast":{"title":"Amanhecer","text":"O horizonte cora de rosa e os primeiros pássaros cruzam o céu."}},
  ],
  // População visual por gerador: vis(n,base,k,cap) = n<=0 ? 0 : min(cap, base + floor(log2(n))*k)
  pop: {
    vagalume:  {base:3,  k:3,  cap:30},
    juncosL:   {base:3,  k:1,  cap:8},
    juncosR:   {base:0,  k:2,  cap:8},
    peixe:     {base:1,  k:1,  cap:8},
    dourado:   {base:1,  k:1,  cap:3},
    estrelas:  {base:15, k:15, cap:200},
    lirio:     {base:3,  k:1,  cap:12},
    sapo:      {base:1,  k:1,  cap:5},
    lua:       {scaleStep:0.08, scaleCap:1.6, haloMin:0.55, haloMax:0.9},
    montanhas: {base:2,  k:1,  cap:4},
    aurora:    {bands2At:10},
  },
  // Bônus ativos: peixe come pedra (max(clique, taxa×fishRateSec) × 2/3/4; cooldown 6 s por peixe em fish.js), brilhos, combo, cadente;
  // lantern: zona da lanterna (raio px, need vagalumes ou needPct dos vivos, buff +25% por buffSec, cooldown; prêmio max(taxa×rateSec, clique×clickMult));
  // village/temple: buff extra da aldeia (era 3) e do templo (era 4).
  bonus: {"fishMult":2,"fishMult10":3,"racaoMult":4,"glintEvery":[60,180],"glintLife":6,"glintRateSec":60,"fishRateSec":1,"comboStep":0.1,"comboCap":2,"comboTol":0.12,"comboMin":0.3,"comboMax":1.5,"shootMult":25,"shootLife":3.5,"shootRadius":40,
           "lantern":{"radius":45,"need":5,"needPct":0.3,"buff":0.25,"buffSec":60,"cooldown":90,"rateSec":90,"clickMult":40},
           "village":{"buff":0.35},"temple":{"buff":0.5}},
  goals: [
    {"id":"primeira_onda","icon":"ic-coll","cond":{"type":"clicks","value":10}},
    {"id":"vagalumes_acordam","icon":"ic-firefly","cond":{"type":"gens","id":"vagalume","value":1}},
    {"id":"cardume","icon":"ic-fish","cond":{"type":"gens","id":"peixe","value":25}},
    {"id":"lua_cheia","icon":"ic-moon","cond":{"type":"gens","id":"lua","value":10}},
    {"id":"mil_ondas","icon":"ic-coll","cond":{"type":"life","value":1000000}},
    {"id":"lago_vivo","icon":"ic-aurora","cond":{"type":"gens","id":"aurora","value":1}},
    {"id":"mare_alta","icon":"ic-shooting","cond":{"type":"rate","value":100000}},
    {"id":"nova_noite","icon":"ic-star","cond":{"type":"prestige","value":1}},
    {"id":"guardiao_lanterna","icon":"ic-firefly","cond":{"type":"bonus","id":"lantern","value":10}},
    {"id":"tres_eras","icon":"ic-moon","cond":{"type":"era","value":3}},
    {"id":"ouvinte","icon":"ic-coll","cond":{"type":"chatter","value":50}},
  ],
};
