// Lago Quieto — modo Idle: dados de economia (gerados pelo painel de balanceamento, prop "L").
// Simulação (2 cliques/s 5 min, 0.5/s até 1 h): 1ª compra 4 s; 5 compras distintas 2m30; maior gap 16 s;
// aurora (10º gerador) 36 min; 1º prestígio 50 min; 2º 1h37.
window.LQ = window.LQ || {};
LQ.IdleData = {
  clickBase: 1,
  gens: [
    {"id":"vagalume","icon":"ic-firefly","unlock":"fireflies","base":8,"growth":1.15,"rate":0.3,"name":"Vagalumes","desc":"mais vagalumes no lago","milestones":[{"at":1,"text":"3 vagalumes acendem"},{"at":5,"text":"9 · pousam nos juncos (se houver)"},{"at":10,"text":"12 · formam constelações"},{"at":25,"text":"enxame de 15"}]},
    {"id":"juncos","icon":"ic-reed","unlock":"wind","base":35,"growth":1.15,"rate":1.4,"name":"Juncos","desc":"mais juncos na margem","milestones":[{"at":1,"text":"3 brotam à esquerda"},{"at":5,"text":"chegam à direita (9)"},{"at":10,"text":"12 juncos"},{"at":25,"text":"margem cheia (15)"}]},
    {"id":"peixe","icon":"ic-fish","unlock":"fish","base":150,"growth":1.15,"rate":6,"name":"Peixes","desc":"+1 peixe · come pedras","milestones":[{"at":1,"text":"come as pedras (×2)"},{"at":5,"text":"3 peixes · saltam sozinhos"},{"at":10,"text":"comem as pedras (×3)"},{"at":25,"text":"cardume de 5"}]},
    {"id":"estrelas","icon":"ic-star","unlock":"stars2","base":600,"growth":1.15,"rate":25,"name":"Estrelas","desc":"céu mais estrelado","milestones":[{"at":1,"text":"15 estrelas"},{"at":5,"text":"céu denso (45)"},{"at":10,"text":"cadentes frequentes"},{"at":25,"text":"75 estrelas"}]},
    {"id":"lua","icon":"ic-moon","unlock":"moon","base":2200,"growth":1.15,"rate":100,"name":"Lua","desc":"lua e halo maiores","milestones":[{"at":5,"text":"lua cheia maior"},{"at":10,"text":"nuvens"},{"at":25,"text":"halo dourado"},{"at":50,"text":"lua enorme"}]},
    {"id":"dourado","icon":"ic-goldfish","unlock":"fish2","base":8000,"growth":1.15,"rate":420,"name":"Peixe dourado","desc":"+1 dourado (até 3)","milestones":[{"at":1,"text":"1º dourado"},{"at":5,"text":"3 dourados"}]},
    {"id":"nevoa","icon":"ic-mountain","unlock":"fog_clear","base":40000,"growth":1.15,"rate":1700,"name":"Montanhas","desc":"cordilheiras ao fundo","milestones":[{"at":1,"text":"névoa abre"},{"at":2,"text":"3ª cordilheira"},{"at":5,"text":"4ª cordilheira"}]},
    {"id":"lirio","icon":"ic-lily","unlock":"lilies","base":200000,"growth":1.15,"rate":7000,"name":"Lírios","desc":"mais lírios na água","milestones":[{"at":1,"text":"3 lírios"},{"at":5,"text":"5 lírios · toque para florir"},{"at":25,"text":"7 lírios"}]},
    {"id":"sapo","icon":"ic-frog","unlock":"frog","base":900000,"growth":1.15,"rate":27000,"name":"Sapos","desc":"+1 sapo coaxando","milestones":[{"at":1,"text":"1º coaxo"},{"at":5,"text":"coro de 3 sapos"},{"at":25,"text":"5 sapos"}]},
    {"id":"aurora","icon":"ic-aurora","unlock":"aurora","base":4000000,"growth":1.15,"rate":100000,"name":"Aurora","desc":"aurora no céu","milestones":[{"at":1,"text":"1ª faixa"},{"at":10,"text":"duas faixas"}]},
  ],
  upgrades: [
    {"id":"vagalume_10","gen":"vagalume","kind":"mult","at":10,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 10"},
    {"id":"vagalume_25","gen":"vagalume","kind":"mult","at":25,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 25"},
    {"id":"vagalume_50","gen":"vagalume","kind":"mult","at":50,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 50"},
    {"id":"vagalume_100","gen":"vagalume","kind":"mult","at":100,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 100"},
    {"id":"vagalume_200","gen":"vagalume","kind":"mult","at":200,"cost":null,"value":2,"name":"Vagalumes","desc":"produção de vagalumes ×2 aos 200"},
    {"id":"juncos_10","gen":"juncos","kind":"mult","at":10,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 10"},
    {"id":"juncos_25","gen":"juncos","kind":"mult","at":25,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 25"},
    {"id":"juncos_50","gen":"juncos","kind":"mult","at":50,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 50"},
    {"id":"juncos_100","gen":"juncos","kind":"mult","at":100,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 100"},
    {"id":"juncos_200","gen":"juncos","kind":"mult","at":200,"cost":null,"value":2,"name":"Juncos","desc":"produção de juncos ×2 aos 200"},
    {"id":"peixe_10","gen":"peixe","kind":"mult","at":10,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 10"},
    {"id":"peixe_25","gen":"peixe","kind":"mult","at":25,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 25"},
    {"id":"peixe_50","gen":"peixe","kind":"mult","at":50,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 50"},
    {"id":"peixe_100","gen":"peixe","kind":"mult","at":100,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 100"},
    {"id":"peixe_200","gen":"peixe","kind":"mult","at":200,"cost":null,"value":2,"name":"Peixes","desc":"produção de peixes ×2 aos 200"},
    {"id":"estrelas_10","gen":"estrelas","kind":"mult","at":10,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 10"},
    {"id":"estrelas_25","gen":"estrelas","kind":"mult","at":25,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 25"},
    {"id":"estrelas_50","gen":"estrelas","kind":"mult","at":50,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 50"},
    {"id":"estrelas_100","gen":"estrelas","kind":"mult","at":100,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 100"},
    {"id":"estrelas_200","gen":"estrelas","kind":"mult","at":200,"cost":null,"value":2,"name":"Estrelas","desc":"produção de estrelas ×2 aos 200"},
    {"id":"lua_10","gen":"lua","kind":"mult","at":10,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 10"},
    {"id":"lua_25","gen":"lua","kind":"mult","at":25,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 25"},
    {"id":"lua_50","gen":"lua","kind":"mult","at":50,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 50"},
    {"id":"lua_100","gen":"lua","kind":"mult","at":100,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 100"},
    {"id":"lua_200","gen":"lua","kind":"mult","at":200,"cost":null,"value":2,"name":"Lua","desc":"produção de lua ×2 aos 200"},
    {"id":"dourado_10","gen":"dourado","kind":"mult","at":10,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 10"},
    {"id":"dourado_25","gen":"dourado","kind":"mult","at":25,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 25"},
    {"id":"dourado_50","gen":"dourado","kind":"mult","at":50,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 50"},
    {"id":"dourado_100","gen":"dourado","kind":"mult","at":100,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 100"},
    {"id":"dourado_200","gen":"dourado","kind":"mult","at":200,"cost":null,"value":2,"name":"Peixe dourado","desc":"produção de peixe dourado ×2 aos 200"},
    {"id":"nevoa_10","gen":"nevoa","kind":"mult","at":10,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 10"},
    {"id":"nevoa_25","gen":"nevoa","kind":"mult","at":25,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 25"},
    {"id":"nevoa_50","gen":"nevoa","kind":"mult","at":50,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 50"},
    {"id":"nevoa_100","gen":"nevoa","kind":"mult","at":100,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 100"},
    {"id":"nevoa_200","gen":"nevoa","kind":"mult","at":200,"cost":null,"value":2,"name":"Montanhas","desc":"produção de montanhas ×2 aos 200"},
    {"id":"lirio_10","gen":"lirio","kind":"mult","at":10,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 10"},
    {"id":"lirio_25","gen":"lirio","kind":"mult","at":25,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 25"},
    {"id":"lirio_50","gen":"lirio","kind":"mult","at":50,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 50"},
    {"id":"lirio_100","gen":"lirio","kind":"mult","at":100,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 100"},
    {"id":"lirio_200","gen":"lirio","kind":"mult","at":200,"cost":null,"value":2,"name":"Lírios","desc":"produção de lírios ×2 aos 200"},
    {"id":"sapo_10","gen":"sapo","kind":"mult","at":10,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 10"},
    {"id":"sapo_25","gen":"sapo","kind":"mult","at":25,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 25"},
    {"id":"sapo_50","gen":"sapo","kind":"mult","at":50,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 50"},
    {"id":"sapo_100","gen":"sapo","kind":"mult","at":100,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 100"},
    {"id":"sapo_200","gen":"sapo","kind":"mult","at":200,"cost":null,"value":2,"name":"Sapos","desc":"produção de sapos ×2 aos 200"},
    {"id":"aurora_10","gen":"aurora","kind":"mult","at":10,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 10"},
    {"id":"aurora_25","gen":"aurora","kind":"mult","at":25,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 25"},
    {"id":"aurora_50","gen":"aurora","kind":"mult","at":50,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 50"},
    {"id":"aurora_100","gen":"aurora","kind":"mult","at":100,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 100"},
    {"id":"aurora_200","gen":"aurora","kind":"mult","at":200,"cost":null,"value":2,"name":"Aurora","desc":"produção de aurora ×2 aos 200"},
    {"id":"click_1","gen":null,"kind":"click","at":null,"cost":15,"value":2,"name":"Pedras pesadas I","desc":"cada pedra rende ×2"},
    {"id":"click_2","gen":null,"kind":"click","at":null,"cost":150,"value":2,"name":"Pedras pesadas II","desc":"cada pedra rende ×2"},
    {"id":"click_3","gen":null,"kind":"click","at":null,"cost":1500,"value":2,"name":"Pedras pesadas III","desc":"cada pedra rende ×2"},
    {"id":"click_4","gen":null,"kind":"click","at":null,"cost":15000,"value":2,"name":"Pedras pesadas IV","desc":"cada pedra rende ×2"},
    {"id":"click_5","gen":null,"kind":"click","at":null,"cost":150000,"value":2,"name":"Pedras pesadas V","desc":"cada pedra rende ×2"},
    {"id":"click_6","gen":null,"kind":"click","at":null,"cost":1500000,"value":2,"name":"Pedras pesadas VI","desc":"cada pedra rende ×2"},
    {"id":"auto_1","gen":null,"kind":"auto","at":null,"cost":800,"value":1,"name":"Orvalho +1/s","desc":"anéis automáticos +1/s"},
    {"id":"auto_2","gen":null,"kind":"auto","at":null,"cost":40000,"value":2,"name":"Orvalho +2/s","desc":"anéis automáticos +2/s"},
    {"id":"offline_12h","gen":null,"kind":"offline","at":null,"cost":15000,"value":12,"name":"Sono 12h","desc":"ganho offline até 12h"},
    {"id":"offline_18h","gen":null,"kind":"offline","at":null,"cost":300000,"value":18,"name":"Sono 18h","desc":"ganho offline até 18h"},
    {"id":"offline_24h","gen":null,"kind":"offline","at":null,"cost":4000000,"value":24,"name":"Sono 24h","desc":"ganho offline até 24h"},
    {"id":"racao","gen":null,"kind":"racao","at":null,"cost":20000,"value":4,"name":"Ração","desc":"pedras viram ração; peixes comem ×4"},
  ],
  prestige: {"K":1500000000},
  // População visual por gerador: vis(n,base,k,cap) = n<=0 ? 0 : min(cap, base + floor(log2(n))*k)
  pop: {
    vagalume:  {base:3,  k:3,  cap:30},
    juncosL:   {base:3,  k:1,  cap:8},
    juncosR:   {base:0,  k:2,  cap:8},
    peixe:     {base:1,  k:1,  cap:8},
    dourado:   {base:1,  k:1,  cap:3},
    estrelas:  {base:15, k:15, cap:200},
    lirio:     {base:3,  k:1,  cap:12},
    sapo:      {base:1,  k:1,  cap:5},
    lua:       {scaleStep:0.08, scaleCap:1.6, haloMin:0.55, haloMax:0.9},
    montanhas: {base:2,  k:1,  cap:4},
    aurora:    {bands2At:10},
  },
  // Bônus ativos: peixe come pedra (max(clique, taxa×fishRateSec) × 2/3/4), brilhos, combo, cadente
  bonus: { fishMult:2, fishMult10:3, racaoMult:4, glintEvery:[60,180], glintLife:6, glintRateSec:60,
           fishRateSec:4, comboStep:0.1, comboCap:2, comboTol:0.12, comboMin:0.3, comboMax:1.5, shootMult:25, shootLife:3.5, shootRadius:40 },
  goals: [
    {"id":"primeira_onda","icon":"ic-coll","cond":{"type":"clicks","value":10}},
    {"id":"vagalumes_acordam","icon":"ic-firefly","cond":{"type":"gens","id":"vagalume","value":1}},
    {"id":"cardume","icon":"ic-fish","cond":{"type":"gens","id":"peixe","value":25}},
    {"id":"lua_cheia","icon":"ic-moon","cond":{"type":"gens","id":"lua","value":10}},
    {"id":"mil_ondas","icon":"ic-coll","cond":{"type":"life","value":1000000}},
    {"id":"lago_vivo","icon":"ic-aurora","cond":{"type":"gens","id":"aurora","value":1}},
    {"id":"mare_alta","icon":"ic-shooting","cond":{"type":"rate","value":100000}},
    {"id":"nova_noite","icon":"ic-star","cond":{"type":"prestige","value":1}},
  ],
};
